import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from '@/components/Weather';
import NotFound from '@/components/NotFound';
import Informations from '@/components/Informations';
import gsap from 'gsap';

export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

      function animate(){
      let tl1 = gsap.timeline({ ease: 'power3.inOut' });
  
      tl1.to('.content', { opacity: 1, duration: 1 });
    }

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      if (e.target.value === false) {
        console.log('error')
      } else {
        setWeather(response.data)
      }
      
      // console.log(response.data)
    });
    animate()
    setCity('')
    setLoading(false)
  };

  if (loading) {
    return <NotFound />;
  } else {
    return (
      <>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-yellow-400 h-screen pt-8">
          {/* <button onClick={fetchWeather}>Fetch data</button> */}
          <div className="max-w-md m-auto border-black border-2 py-8 rounded-3xl px-5">
            <div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-black z-10">
              <form 
              onSubmit={fetchWeather}
              className="flex justify-between items-center w-full bg-transparent border border-2 border-black rounded-lg p-3 m-auto">
                <div>
                  <input 
                  onChange={(e) => setCity(e.target.value)}
                  className="bg-transparent outline-none text-black w-full focus:outline-none placeholder:text-black placeholder:opacity-60" 
                  type="text" 
                  placeholder="Search city" 
                  />
                </div>
                <button className="text-black" onClick={fetchWeather}>
                  <BsSearch size={20} />
                  </button>
              </form>
            </div>

            <div className="content">
              {weather.main && <Weather data={weather} />}

              {weather.main && <Informations data={weather} />}
            </div>
          </div>
        </main>
      </>
    )

  }

}
